use_frameworks!

platform :ios, '8.0'

target 'SHCommonNetworking_Example' do
  pod 'SHCommonNetworking', :path => '../'

  target 'SHCommonNetworking_Tests' do
    inherit! :search_paths

    
  end
end
